# Generated by Django 5.1.3 on 2024-12-22 02:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tagi',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('title', models.CharField(max_length=150, verbose_name='Tytuł:')),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data:')),
                ('excerpt', models.TextField(validators=[django.core.validators.MinLengthValidator, django.core.validators.MaxLengthValidator(250)], verbose_name='skrót')),
                ('ingredients', models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Składniki:')),
                ('prepare', models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Sposób przygotowania:')),
                ('image', models.ImageField(upload_to='dishes')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor:')),
                ('tags', models.ManyToManyField(to='blog.tagmodel', verbose_name='Tag:')),
            ],
            options={
                'verbose_name_plural': 'Posty',
            },
        ),
        migrations.CreateModel(
            name='UserCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Treść:')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.postmodel', verbose_name='Post:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik:')),
            ],
            options={
                'verbose_name_plural': 'Komentarze',
            },
        ),
    ]
