# Generated by Django 5.1.3 on 2024-12-30 01:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nazwa użytkownika')),
                ('email', models.EmailField(max_length=254, verbose_name='Email:')),
                ('password', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Hasło:`')),
                ('email_is_verificated', models.BooleanField(default=False, verbose_name='Weryfikacja email:')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='usercommentmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.postmodel', verbose_name='Post:'),
        ),
    ]
