# Generated by Django 5.1.3 on 2024-12-30 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_customuser_password1_alter_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password1',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default=False, max_length=150, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Hasło:'),
        ),
    ]
