# Generated by Django 5.1.3 on 2024-12-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_customusermodel_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='is_verficated',
            field=models.BooleanField(default=False),
        ),
    ]
